import sys
import os


def build_kv_file(kvFilename):
	# open file and write the header
	file = open("npc_" + kvFilename + "_custom.txt", "w")
	write_header(file, kvFilename)

	# append all the files
	kvDir = "./" + kvFilename + "/"
	for subFile in os.listdir(kvDir):
		with open(kvDir + subFile) as f:
			file.write("\n	// " + subFile + "\n")
			for line in f:
				file.write(line)

	# close file
	write_end(file)
	file.close()


def write_header(file, kvFilename):
	file.write("// This file was autogenerated\n")
	file.write("// To change it's contents you should edit the files in ./" + kvFilename +"/\n")
	file.write("// Then run \"python build_kv.py " + kvFilename + "\"\n\n")
	if kvFilename == "units":
		file.write("\"DOTAUnits\"\n")
	else:
		file.write("\"DOTAAbilities\"\n")
	file.write("{\n")


def write_end(file):
	file.write("\n}")


def main():
	# check for valid options
	valid_options = ["abilities", "items", "units", "all"]
	if len(sys.argv) < 1 or (not sys.argv[1] in valid_options):
		print("Invalid arguments!")
		print("Usage: build_kv <abilities/items/units/all>")
		return

	# get option
	option = sys.argv[1]
	files = []
	if option == "all":
		files = ["abilities", "items", "units"]
	else:
		files = [option]

	# iterate through all directiories and generate the kv files
	for kvFilename in files:
		if os.path.exists("./" + kvFilename + "/"):
			build_kv_file(kvFilename)
		else:
			print("Couldn't find the folder for " + kvFilename)

if __name__ == "__main__":
	main()